export type GetTopCoins = {
  Data: Data;
  Err: Err;
}
export type Data = {
  STATS: STATS;
  LIST?: (LISTEntity)[] | null;
}
export type STATS = {
  PAGE: number;
  PAGE_SIZE: number;
  TOTAL_ASSETS: number;
}
export type LISTEntity = {
  ID: number;
  TYPE: string;
  ID_LEGACY?: number | null;
  ID_PARENT_ASSET?: number | null;
  ID_ASSET_ISSUER?: number | null;
  SYMBOL: string;
  URI: string;
  ASSET_TYPE: string;
  ASSET_ISSUER_NAME?: string | null;
  PARENT_ASSET_SYMBOL?: string | null;
  CREATED_ON: number;
  UPDATED_ON: number;
  PUBLIC_NOTICE?: string | null;
  NAME: string;
  LOGO_URL: string;
  LAUNCH_DATE: number;
  PREVIOUS_ASSET_SYMBOLS?: null;
  ASSET_ALTERNATIVE_IDS?: (ASSETALTERNATIVEIDSEntity)[] | null;
  ASSET_DESCRIPTION_SNIPPET?: string | null;
  ASSET_DECIMAL_POINTS?: number | null;
  SUPPLY_MAX: number;
  SUPPLY_ISSUED: number;
  SUPPLY_TOTAL: number;
  SUPPLY_CIRCULATING?: number | null;
  SUPPLY_FUTURE: number;
  SUPPLY_LOCKED?: number | null;
  SUPPLY_BURNT: number;
  SUPPLY_STAKED?: number | null;
  LAST_BLOCK_MINT?: number | null;
  LAST_BLOCK_BURN?: null;
  PRICE_USD: number;
  PRICE_USD_SOURCE: string;
  PRICE_USD_LAST_UPDATE_TS: number;
  PRICE_CONVERSION_ASSET: PRICECONVERSIONASSET;
  PRICE_CONVERSION_RATE: number;
  PRICE_CONVERSION_VALUE: number;
  PRICE_CONVERSION_SOURCE: string;
  PRICE_CONVERSION_LAST_UPDATE_TS: number;
  MKT_CAP_PENALTY?: number | null;
  CIRCULATING_MKT_CAP_USD: number;
  TOTAL_MKT_CAP_USD: number;
  CIRCULATING_MKT_CAP_CONVERSION: number;
  TOTAL_MKT_CAP_CONVERSION: number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_DIRECT_USD": number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_DIRECT_USD": number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_USD": number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_USD": number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_CONVERSION": number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_CONVERSION": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_TOP_TIER_DIRECT_USD": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_DIRECT_USD": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_TOP_TIER_USD": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_USD": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_TOP_TIER_CONVERSION": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_CONVERSION": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_TOP_TIER_DIRECT_USD": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_DIRECT_USD": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_TOP_TIER_USD": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_USD": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_TOP_TIER_CONVERSION": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_CONVERSION": number;
  "SPOT_MOVING_24_HOUR_CHANGE_USD": number;
  "SPOT_MOVING_24_HOUR_CHANGE_PERCENTAGE_USD": number;
  "SPOT_MOVING_24_HOUR_CHANGE_CONVERSION": number;
  "SPOT_MOVING_24_HOUR_CHANGE_PERCENTAGE_CONVERSION": number;
  "SPOT_MOVING_7_DAY_CHANGE_USD": number;
  "SPOT_MOVING_7_DAY_CHANGE_PERCENTAGE_USD": number;
  "SPOT_MOVING_7_DAY_CHANGE_CONVERSION": number;
  "SPOT_MOVING_7_DAY_CHANGE_PERCENTAGE_CONVERSION": number;
  "SPOT_MOVING_30_DAY_CHANGE_USD": number;
  "SPOT_MOVING_30_DAY_CHANGE_PERCENTAGE_USD": number;
  "SPOT_MOVING_30_DAY_CHANGE_CONVERSION": number;
  "SPOT_MOVING_30_DAY_CHANGE_PERCENTAGE_CONVERSION": number;
  TOPLIST_BASE_RANK: TOPLISTBASERANK;
  ROOT_ASSET_ID?: number | null;
  ROOT_ASSET_SYMBOL?: string | null;
  ROOT_ASSET_TYPE?: string | null;
}
export type ASSETALTERNATIVEIDSEntity = {
  NAME: string;
  ID: string;
}
export type PRICECONVERSIONASSET = {
  ID: number;
  SYMBOL: string;
  ASSET_TYPE: string;
}
export type TOPLISTBASERANK = {
  CREATED_ON: number;
  LAUNCH_DATE: number;
  CIRCULATING_MKT_CAP_USD: number;
  TOTAL_MKT_CAP_USD: number;
  "SPOT_MOVING_24_HOUR_QUOTE_VOLUME_USD": number;
  "SPOT_MOVING_7_DAY_QUOTE_VOLUME_USD": number;
  "SPOT_MOVING_30_DAY_QUOTE_VOLUME_USD": number;
}
export type Err = {
}
