export interface CoinEntity_Gecko {
  id: string;
  symbol: string;
  name: string;
  image: string;
  current_price: number;
  market_cap: number;
  market_cap_rank: number;
  fully_diluted_valuation: number;
  total_volume: number;
  high_24h: number;
  low_24h: number;
  price_change_24h: number;
  price_change_percentage_24h: number;
  market_cap_change_24h: number;
  market_cap_change_percentage_24h: number;
  circulating_supply: number;
  total_supply: number;
  max_supply: number;
  ath: number;
  ath_change_percentage: number;
  ath_date: Date;
  atl: number;
  atl_change_percentage: number;
  atl_date: Date;
  roi: null;
  last_updated: Date;
}

export interface CoinEntity_Compare {
  ID: number;
  TYPE: string;
  ID_LEGACY?: number | null;
  ID_PARENT_ASSET?: number | null;
  ID_ASSET_ISSUER?: number | null;
  SYMBOL: string;
  URI: string;
  ASSET_TYPE: string;
  ASSET_ISSUER_NAME?: string | null;
  PARENT_ASSET_SYMBOL?: string | null;
  CREATED_ON: number;
  UPDATED_ON: number;
  PUBLIC_NOTICE?: string | null;
  NAME: string;
  LOGO_URL: string;
  LAUNCH_DATE: number;
  PREVIOUS_ASSET_SYMBOLS?: null;
  ASSET_DESCRIPTION_SNIPPET?: string | null;
  ASSET_DECIMAL_POINTS?: number | null;
  SUPPLY_MAX: number;
  SUPPLY_ISSUED: number;
  SUPPLY_TOTAL: number;
  SUPPLY_CIRCULATING?: number | null;
  SUPPLY_FUTURE: number;
  SUPPLY_LOCKED?: number | null;
  SUPPLY_BURNT: number;
  SUPPLY_STAKED?: number | null;
  LAST_BLOCK_MINT?: number | null;
  LAST_BLOCK_BURN?: null;
  PRICE_USD: number;
  PRICE_USD_SOURCE: string;
  PRICE_USD_LAST_UPDATE_TS: number;
  PRICE_CONVERSION_RATE: number;
  PRICE_CONVERSION_VALUE: number;
  PRICE_CONVERSION_SOURCE: string;
  PRICE_CONVERSION_LAST_UPDATE_TS: number;
  MKT_CAP_PENALTY?: number | null;
  CIRCULATING_MKT_CAP_USD: number;
  TOTAL_MKT_CAP_USD: number;
  CIRCULATING_MKT_CAP_CONVERSION: number;
  TOTAL_MKT_CAP_CONVERSION: number;
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_DIRECT_USD: number;
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_DIRECT_USD: number;
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_USD: number;
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_USD: number;
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_CONVERSION: number;
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_CONVERSION: number;
  SPOT_MOVING_7_DAY_QUOTE_VOLUME_TOP_TIER_DIRECT_USD: number;
  SPOT_MOVING_7_DAY_QUOTE_VOLUME_DIRECT_USD: number;
  SPOT_MOVING_7_DAY_QUOTE_VOLUME_TOP_TIER_USD: number;
  SPOT_MOVING_7_DAY_QUOTE_VOLUME_USD: number;
  SPOT_MOVING_7_DAY_QUOTE_VOLUME_TOP_TIER_CONVERSION: number;
  SPOT_MOVING_7_DAY_QUOTE_VOLUME_CONVERSION: number;
  SPOT_MOVING_30_DAY_QUOTE_VOLUME_TOP_TIER_DIRECT_USD: number;
  SPOT_MOVING_30_DAY_QUOTE_VOLUME_DIRECT_USD: number;
  SPOT_MOVING_30_DAY_QUOTE_VOLUME_TOP_TIER_USD: number;
  SPOT_MOVING_30_DAY_QUOTE_VOLUME_USD: number;
  SPOT_MOVING_30_DAY_QUOTE_VOLUME_TOP_TIER_CONVERSION: number;
  SPOT_MOVING_30_DAY_QUOTE_VOLUME_CONVERSION: number;
  SPOT_MOVING_24_HOUR_CHANGE_USD: number;
  SPOT_MOVING_24_HOUR_CHANGE_PERCENTAGE_USD: number;
  SPOT_MOVING_24_HOUR_CHANGE_CONVERSION: number;
  SPOT_MOVING_24_HOUR_CHANGE_PERCENTAGE_CONVERSION: number;
  SPOT_MOVING_7_DAY_CHANGE_USD: number;
  SPOT_MOVING_7_DAY_CHANGE_PERCENTAGE_USD: number;
  SPOT_MOVING_7_DAY_CHANGE_CONVERSION: number;
  SPOT_MOVING_7_DAY_CHANGE_PERCENTAGE_CONVERSION: number;
  SPOT_MOVING_30_DAY_CHANGE_USD: number;
  SPOT_MOVING_30_DAY_CHANGE_PERCENTAGE_USD: number;
  SPOT_MOVING_30_DAY_CHANGE_CONVERSION: number;
  SPOT_MOVING_30_DAY_CHANGE_PERCENTAGE_CONVERSION: number;
  ROOT_ASSET_ID?: number | null;
  ROOT_ASSET_SYMBOL?: string | null;
  ROOT_ASSET_TYPE?: string | null;
}
